name = "mhp"
compatibility_date = "2024-01-01"

[build]
command = "pnpm run build"
[build.upload]
format = "service-worker"

[[build.steps]]
name = "node"
version = "20.11.0"

[env.production]
NODE_VERSION = "20.11.0"